version: '2'
services:
  warehouse:
    image: postgres:13
    container_name: IMDB_warehouse
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./Data:/var/lib/Data
      # copy the sql script to create tables
      # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: always
    ports:
      - "5432:5432"
  dashboard:
    image: metabase/metabase
    container_name: IMDB_dashboard
    ports:
      - "3000:3000"
    volumes:
    - ./dashboard-volume:/var/lib/metabase/data